### ISSUE TITLE
Binder.writeBean() and writeBeanIfValid() should write only changed values

### ISSUE THREAD

**Issue by dnDeveloper** [vaadin/framework#9128]
Binder.writeBean() and writeBeanIfValid() actually call all setters, even if the Bean properties are not changed.

For performance reasons setters should only be called, if Bean properties are changed. So setters do not have to care about the case, that value does not change.

In Binder.doWriteIfValid the old values of the Bean properties are stored. Maybe these old value or a status can be stored in the Binder.BindingImpl and used in Binder.BindingImpl.writeFieldValue() to check, if setter should be called or not.

**Comment by dnDeveloper** [comment]
We have implemented a solution outside of Binder. So we do not need this anymore.

**Comment by tsuoanttila** [comment]
This is a fundamental problem in the design of the "buffered" Binder, as it does not store the information of what bean were the values read from and the idea to allow saving the state of the binder to any arbitrary bean. The issue is still kind of valid, but the solution is not easy to do without some massive changes to the Binder itself. 

Good to hear that you have found your way around this isssue!
